name: Video Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install pillow requests

      - name: Run render
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python render.py

      - name: Create MP4
        run: |
          ffmpeg -y -framerate 1 -i frame%d.png \
          -c:v libx264 -pix_fmt yuv420p output.mp4

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: output.mp4
